version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into AWS ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 224758575768.dkr.ecr.ap-southeast-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Building Docker image...
      - docker build -t 224758575768.dkr.ecr.ap-southeast-1.amazonaws.com/nestjs-app:$IMAGE_TAG .
      - docker tag 224758575768.dkr.ecr.ap-southeast-1.amazonaws.com/nestjs-app:$IMAGE_TAG 224758575768.dkr.ecr.ap-southeast-1.amazonaws.com/nestjs-app:$COMMIT_HASH

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 224758575768.dkr.ecr.ap-southeast-1.amazonaws.com/nestjs-app:$IMAGE_TAG
      - docker push 224758575768.dkr.ecr.ap-southeast-1.amazonaws.com/nestjs-app:$COMMIT_HASH
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"nestjs-container","imageUri":"%s"}]' 224758575768.dkr.ecr.ap-southeast-1.amazonaws.com/nestjs-app:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
